# Netlify Configuration for Mineral Map CMS
# Vite + React + TypeScript Build Configuration

[build]
  # Build command - runs Vite build only (skip strict TypeScript type checking)
  # This allows the build to succeed even with minor TypeScript errors
  # Run 'npm run build' locally to catch errors before deploying
  command = "vite build"

  # Directory that contains the built site (Vite builds to 'dist' by default)
  publish = "dist"

  # Node.js version - use a recent LTS version
  # This ensures compatibility with your dependencies
  NODE_VERSION = "20"

[build.environment]
  # Disable Netlify's automatic Next.js detection
  # (prevents confusion with React Router setup)
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Redirect rules for Single Page Application (SPA)
# This ensures React Router works correctly on Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Function settings (if you add Netlify Functions later)
[functions]
  node_bundler = "esbuild"
